name: FreeShen Config Collector

on:
  schedule:
    - cron: '0 0 * * *' # هر روز ساعت 00:00 UTC
  push:
    branches: [ main ]

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: python src/Main.py
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/*
        git commit -m "Update configs by ☬SHΞN™" || echo "No changes to commit"
        git push
